### ISSUE TITLE
Beam decoding problem

### ISSUE THREAD

**Issue by chatzikon** [nasib-ullah/video-captioning-models-in-Pytorch#1]
The beam decoding at mean pooling is not working. I think it is because of the wrong size of the return tensor (caps_text). Instead of a size (batch size, max_length), it has size (batch_size, beam length). Could you fix it?

**Comment by nasib-ullah** [comment]
Hi @chatzikon there was some problem with the code. I have updated it to the latest version. It's working now. Still for GRU beam and Greedy is giving the same result. In the case of LSTM, the METEOR score for Beam decoding is less than greedy, though the BLEU score is better.
