### ISSUE TITLE
Feature shape don't match in SA-LSTM beam decoding

### ISSUE THREAD

**Issue by davidluciolu** [nasib-ullah/video-captioning-models-in-Pytorch#3]
find that
```
if self.cfg.opt_encoder:
    feats = self.encoder(feats) 
```
should be added in function `BeamDecoding` of `models/SA_LSTM/model.py`, to project visual features

**Comment by nasib-ullah** [comment]
Hi, Thank you very much for pointing it out. I have fixed the bug and updated the code.
