### ISSUE TITLE
About motion feature of dataset

### ISSUE THREAD

**Issue by Jack2Lu** [nasib-ullah/video-captioning-models-in-Pytorch#6]
The framework is very nice and I downloaded the motion feature extracted from resnext-101, but found the shape of feature are different for each video. So when I run the code, it goes wrong ,
![image](https://github.com/nasib-ullah/video-captioning-models-in-Pytorch/assets/134119081/35a3db97-1da6-4cf6-92db-48d3143793c8)
 then I wonder if there's something wrong with motion feature of MSVD and how you extract the motion feature. It's important for me, I hope for your help.

**Comment by nasib-ullah** [comment]
Hi, for motion features with different shape, change accordingly in config.py file 
https://github.com/nasib-ullah/video-captioning-models-in-Pytorch/blob/main/config.py#L383
